### ISSUE TITLE
&lt;space&gt; 35_MD_FC.xml

### ISSUE THREAD

**Issue by glorieux-f** [ebalzac/FC#1]
Dans 35_MD_FC.xml, j'ai trouvé une bizarrerie de conversion XML
&lt;space&gt;

**Comment by maximeperret** [comment]
Merci Fred de l'avoir signalé ici ! Je m'en occupe enfin (il n'est jamais trop tard), mais c'est que nous avons mis du temps à trouver la solution. Je corrige le xml maintenant !
